"""Initial migration

Revision ID: 5a968697fa31
Revises: 
Create Date: 2024-09-06 17:16:46.017502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a968697fa31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_backup')
    op.drop_table('reviews')
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('validation',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('availability',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('booked',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('booked',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('availability',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('validation',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review', sa.VARCHAR(length=10000), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey')
    )
    op.create_table('schedule_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('availability', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('booked', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
