"""empty message

Revision ID: b54a48b008a7
Revises: 5a968697fa31
Create Date: 2024-09-06 19:12:31.778035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54a48b008a7'
down_revision = '5a968697fa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('schedule_backup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('availability', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('booked', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review', sa.VARCHAR(length=10000), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey')
    )
    # ### end Alembic commands ###
