# Generated by Django 5.1.1 on 2024-09-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comments_bid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="comments",
            new_name="Comment",
        ),
    ]
