# Generated by Django 5.1.1 on 2024-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_comments_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                default="web_app/Project2/commerce/commerce/media/photos/default_image.png",
                upload_to="photos/",
            ),
        ),
    ]
