# Generated by Django 5.1.1 on 2024-10-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_image_wishlist"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Wishlist",
            new_name="Watchlist",
        ),
        migrations.RenameField(
            model_name="watchlist",
            old_name="wished",
            new_name="watching",
        ),
    ]
