# Generated by Django 5.1.1 on 2024-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_listing_winner_alter_listing_listed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="closed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
