# Generated by Django 5.1.1 on 2024-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bookings", "0005_remove_user_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Stitlepecific permissions for this user.",
                related_name="custom_user_permissions_set",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={("slot", "day")},
        ),
    ]
