# Generated by Django 5.1.1 on 2024-11-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_timetable_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together=set(),
        ),
    ]
