# Generated by Django 5.1.1 on 2024-12-02 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_alter_timetable_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="capacity",
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booked_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Participant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Class_name",
                        to="bookings.timetable",
                    ),
                ),
            ],
        ),
    ]
