# Generated by Django 5.1.1 on 2024-12-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_timetable_capacity_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fit_class",
            old_name="capacity",
            new_name="CAPACITY",
        ),
    ]
