# Generated by Django 5.1.1 on 2024-12-03 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0016_alter_fit_class_teacher"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="fit_class",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_name",
                to="bookings.club",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Day_of_class",
                to="bookings.day",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Class_name",
                to="bookings.fit_class",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Class_time_slot",
                to="bookings.time",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                fields=("slot", "day", "club"), name="unique_slot_day_club"
            ),
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gte", 0)), name="positive_capacity"
            ),
        ),
    ]
