# Generated by Django 5.1.4 on 2024-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0023_waiting_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="waiting_list",
            name="que",
            field=models.IntegerField(default=0),
        ),
    ]
