# Generated by Django 5.1.4 on 2024-12-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0028_remove_notification_claimed_notification_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
