# Generated by Django 5.1.4 on 2024-12-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0033_time_duration_time_timestamp_alter_placeholder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="timestampId",
            field=models.IntegerField(default=1),
        ),
    ]
