# Generated by Django 5.1.4 on 2024-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0036_remove_timetable_unique_slot_day_club_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="class_name",
        ),
        migrations.AddField(
            model_name="history",
            name="club",
            field=models.CharField(default="test", max_length=10),
        ),
        migrations.AddField(
            model_name="history",
            name="day",
            field=models.CharField(default="test", max_length=10),
        ),
        migrations.AddField(
            model_name="history",
            name="fit_class",
            field=models.CharField(default="test", max_length=20),
        ),
        migrations.AddField(
            model_name="history",
            name="time",
            field=models.CharField(default="test", max_length=20),
        ),
    ]
