# Generated by Django 5.1.4 on 2024-12-25 16:18

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0037_remove_history_class_name_history_club_history_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="date",
            field=models.DateField(auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
    ]
