# Generated by Django 5.1.4 on 2024-12-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0038_day_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="time",
            name="timestamp",
        ),
    ]
