# Generated by Django 5.1.4 on 2024-12-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0043_day_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="timestamp",
        ),
    ]
