# Generated by Django 5.1.4 on 2024-12-25 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0047_alter_time_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="date_today",
        ),
        migrations.AlterField(
            model_name="time",
            name="timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
