# Generated by Django 5.1.4 on 2024-12-26 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0049_day_date_today_alter_time_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="time",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
