# Generated by Django 5.1.4 on 2024-12-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0052_placeholder_all"),
    ]

    operations = [
        migrations.RenameField(
            model_name="placeholder",
            old_name="user",
            new_name="user1",
        ),
    ]
