# Generated by Django 5.1.4 on 2024-12-31 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0053_rename_user_placeholder_user1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeholder",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="WL_user1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
