# Generated by Django 5.1.1 on 2025-03-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resting', '0002_alter_schedule_booked_alter_schedule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
