# Generated by Django 5.1.1 on 2025-03-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resting', '0003_alter_schedule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
