# Generated by Django 5.1.1 on 2025-03-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resting', '0005_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_plus',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user_plus',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_plus',
            name='hash',
        ),
    ]
