# Generated by Django 5.1.1 on 2025-03-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resting', '0006_remove_user_plus_admin_remove_user_plus_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_plus',
            name='reset',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
