# Generated by Django 5.1.1 on 2025-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resting', '0008_alter_gift_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='booked',
            field=models.CharField(default='False', max_length=255),
        ),
    ]
