# Generated by Django 5.1.1 on 2025-03-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resting', '0009_alter_schedule_booked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'time']},
        ),
    ]
