# Generated by Django 5.1.1 on 2024-12-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_alter_timetable_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={("slot", "day")},
        ),
    ]
