# Generated by Django 5.1.1 on 2024-12-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_rename_capacity_fit_class_capacity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
