# Generated by Django 5.1.1 on 2024-12-03 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0015_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fit_class",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
