# Generated by Django 5.1.1 on 2024-12-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0017_alter_timetable_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
