# Generated by Django 5.1.1 on 2024-12-04 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0021_rename_booking_bookings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bookings",
            new_name="Booking",
        ),
    ]
