# Generated by Django 5.1.4 on 2024-12-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0027_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="claimed",
        ),
        migrations.AddField(
            model_name="notification",
            name="seen",
            field=models.BooleanField(default=True),
        ),
    ]
