# Generated by Django 5.1.4 on 2024-12-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0030_placeholder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="placeholder",
            old_name="user",
            new_name="token",
        ),
    ]
