# Generated by Django 5.1.4 on 2024-12-23 12:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0032_placeholder_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="time",
            name="duration",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="time",
            name="timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="placeholder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="WL_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
