# Generated by Django 5.1.4 on 2024-12-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0034_day_timestampid"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
