# Generated by Django 5.1.4 on 2024-12-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0035_timetable_is_active"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timetable",
            name="unique_slot_day_club",
        ),
        migrations.AlterField(
            model_name="history",
            name="class_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                fields=("slot", "day", "club", "is_active"), name="unique_slot_day_club"
            ),
        ),
    ]
