# Generated by Django 5.1.4 on 2024-12-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0040_remove_day_date_time_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="time",
            name="timestamp",
        ),
    ]
