# Generated by Django 5.1.4 on 2024-12-25 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0042_time_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
