# Generated by Django 5.1.4 on 2024-12-25 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0044_remove_day_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="date_today",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
