# Generated by Django 5.1.4 on 2024-12-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0046_alter_day_date_today"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="timestamp",
            field=models.TimeField(default=models.CharField(max_length=10)),
        ),
    ]
